import { motion } from 'framer-motion';
import { Metadata } from 'next';
import Link from 'next/link';
import { SidebarCustomized } from '../components';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
	return (
		<main className={cn('rounded-md flex flex-col md:flex-row w-full flex-1 overflow-hidden', 'h-screen')}>
			<SidebarCustomized />
			<div className='flex flex-1'>
				<div className='p-2 md:p-10 border border-neutral-200 dark:border-neutral-700 bg-white dark:bg-neutral-900 flex flex-col gap-2 flex-1 w-full h-full'>
					{children}
				</div>
			</div>
		</main>
	);
}
export const Logo = () => {
	return (
		<Link
			href='#'
			className='font-normal flex space-x-2 items-center text-sm text-black py-1 relative z-20'>
			<div className='h-5 w-6 bg-black dark:bg-white rounded-br-lg rounded-tr-sm rounded-tl-lg rounded-bl-sm flex-shrink-0' />
			<motion.span
				initial={{ opacity: 0 }}
				animate={{ opacity: 1 }}
				className='font-medium text-black dark:text-white whitespace-pre'>
				Acet Labs
			</motion.span>
		</Link>
	);
};
